<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>UniProtocol.Crypto.Tests</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\UniProtocol.Crypto\UniProtocol.Crypto.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Vectors\**\*.*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
