<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>UniProtocol.Protocol.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\UniProtocol.Protocol\UniProtocol.Protocol.csproj" />
  </ItemGroup>

</Project>
