<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>unip</AssemblyName>
    <RootNamespace>UniProtocol.Cli</RootNamespace>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UniProtocol\UniProtocol.csproj" />
  </ItemGroup>

</Project>
